### ISSUE TITLE
review results

### ISSUE THREAD

**Issue by ashwintiwari88** [LintangWisesa/Express-Bottender-Messenger-MongoDB#1]
[-] test & linting package on dependencies
[-] no test
[-] no folder structure, all in one file
[-] repeated function when saving to db
[+-] have linting setup but not using it
[+-] logic flow (the user and state / question id) is handled by bottender. it always count for birthday days left altho user answer no
[+] well documented
[+] great porto! lecturer - tech tutorial youtube - many repo for tech exploration - tech sharing (and yes, he share his submission too link)

summary:

@LintangWisesa 

it is a unique submission. the bot is build on top of framework (bottender) but overall the minuses outweighed your plusses .

we have put time into your review,  hope you can see that.

best of luck in your next play!

**Comment by LintangWisesa** [comment]
Thanks for your time reviewing this project.
